### ISSUE TITLE
sequencing summary /read until decision stats

### ISSUE THREAD

**Issue by JensUweUlrich** [richardmleggett/adaptive_sampling#1]
Hi,

I just have a short question: Could you also provide the read_until_decision_statistics and/or sequencing summary statistics CSV files for the runs? I would like to do some statistical analysis on adaptive sampling data sets but also need information about which reads were unblocked.

Thanks
Jens

**Comment by richardmleggett** [comment]
Hi Jens,
Yep, we'll try and do this in the next few days.
All the best,
Richard

**Comment by JensUweUlrich** [comment]
Hi Richard,

That was fast! Thanks a lot. 

Best
Jens

**Comment by richardmleggett** [comment]
Hi Jens,

Sam has uploaded the sequencing summary files to: https://zenodo.org/record/5417058#.YTKGNS1Q1B0

I've also put a link to that in this GitHub.

Thanks,
Richard

**Comment by JensUweUlrich** [comment]
Thanks Richard & Sam. This is much appreciated!

Now I can try to run the adaptive sampling scripts from your Preprint.

Best
Jens
